# Generated by Django 4.0 on 2021-12-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0003_alter_transaction_dt_insert_alter_transaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dt_insert',
            field=models.DateTimeField(),
        ),
    ]
